- name: Disable autostart in user crontab
  hosts: all
  become: yes
  vars:
    cron_file: /var/spool/cron/crontabs/jetson   # Debian/Ubuntu user crontab path
  tasks:
    - name: Check if the jetson crontab file exists
      ansible.builtin.stat:
        path: "{{ cron_file }}"
      register: cron_stat

    - name: Comment out the @reboot app.py line (only if file exists)
      ansible.builtin.replace:
        path: "{{ cron_file }}"
        regexp: '^(?!#)(@reboot\s+sleep 3 && whoami && pulseaudio --start && sleep 2 && XDG_RUNTIME_DIR=/run/user/1000 ~/ugv_jetson/ugv-env/bin/python ~/ugv_jetson/app.py.*)$'
        replace: '# \1'
        backup: yes
      when: cron_stat.stat.exists

    # Keep Debian/Ubuntu cron happy: correct owner/perms on user crontab files
    - name: Ensure crontab ownership and permissions
      ansible.builtin.file:
        path: "{{ cron_file }}"
        owner: jetson
        group: crontab
        mode: '0600'
      when: cron_stat.stat.exists

    # Reboot system
    - name: Reboot if crontab was modified
      ansible.builtin.reboot:
        msg: "Rebooting after disabling autostart in crontab"
        reboot_timeout: 300
      when: cron_stat.stat.exists and (ansible_facts['pkg_mgr'] is defined)
