# playbooks/set_hostname.yml
- name: Set Hostname
  hosts: all
  become: yes

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts for local resolution
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }}"
    
    - name: Update /etc/hosts for local resolution
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }}"
    
    - name: Set password for jetson user
      become: true
      ansible.builtin.user:
        name: jetson
        password: "{{ 'uvarobolab' | password_hash('sha512') }}"